### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by padmaja-22**

### CODE REVIEW

**Comment by padmaja-22** [comment]
Can you please check once and merge:)

**Review by bobluppes — CHANGES_REQUESTED** [review]
Hi @padmaja-22, thanks for the PR.

The added requirements are looking good.

It is preferred to use clear statements in the readme file, for instance "the requirements are" instead of "the requirements would be". This was not clear beforehand and I will make sure to add it in the contributions section.

If you can make the minor adjustment I will merge it into the project.

Thanks and much appreciated!

**Comment by padmaja-22** [comment]
Will do it asap!

**Review by bobluppes — APPROVED** [review]
Thanks for the update, will merge it into the master branch!

**Comment by padmaja-22** [comment]
Thank you so much @bobluppes. Would love to contribute further more:)

**Comment by bobluppes** [comment]
@padmaja-22, no problem. I can check later today if we have some more small tasks I can open an issue for. Will let you know!

**Comment by padmaja-22** [comment]
Is this repo not participating in Hactober fest?

**Comment by bobluppes** [comment]
@padmaja-22 I added the hacktoberfest label to the issue about an hour ago, so I assume it takes a bit of time for it to be reconized. I will check later today to make sure it is added.

**Comment by padmaja-22** [comment]
Okay! Was surprised seeing invalid PR on my hactober fest profile. Make sure it will be recognised 😄

**Comment by bobluppes** [comment]
Oh, the invalid PR is due to the requested changes on the first attempt. Now that it is merged I expect it to be valid soon :)

**Comment by padmaja-22** [comment]
Cool!!

**Comment by padmaja-22** [comment]
@bobluppes Add **"hactoberfest"**  in topics and label to your repo. It makes merge eligible

**Comment by bobluppes** [comment]
Hey, I just did. I also added the "hacktoberfest-accepted" label to the PR just to be sure. Please let me know if this works for you

**Comment by padmaja-22** [comment]
No it is still ineligible.

**Comment by bobluppes** [comment]
It should work now

**Comment by padmaja-22** [comment]
Great! Thanks @bobluppes

**Pull request merged**
